# Configurations
title:            Macarte - MI
longtitle:        Macarte - Modèle d'interface
author:           Viglino
email:            jean-marc.viglino@ign.Fr
description: >
  Macarte - Modèle d'interface
  
version:          1.0

url:              'https://viglino.github.io'
baseurl:          '/Macarte-MI'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: just-the-docs/just-the-docs

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 Jean-Marc Viglino - <a href=\"https://github.com/Viglino/Macarte-MI/blob/main/LICENSE.txt\">CC-by-4.0.</a>

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/images/favicon.ico
