# Configurations
title:            Macarte-MI
longtitle:        Macarte - Modèle d'interface
author:           Viglino
email:            jean-marc.viglino@ign.Fr
description: >
  Macarte - Modèle d'interface
  
version:          1.0

url:              'https://viglino.github.io'
baseurl:          '/Macarte-MI'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: just-the-docs/just-the-docs

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/images/favicon.ico
